/** Canonical log event types. Missing toggle keys default to enabled. */
export const LOG_EVENT_TYPES = [
  // Members
  "member_join",
  "member_leave",
  "member_kick",
  "member_ban",
  "member_unban",
  "member_timeout",
  "member_nick",
  "member_roles",
  // Messages
  "message_edit",
  "message_delete",
  "message_bulk_delete",
  "message_pin",
  // Channels / threads
  "channel_create",
  "channel_delete",
  "channel_update",
  "thread_create",
  "thread_update",
  "thread_delete",
  // Roles / guild structure
  "role_create",
  "role_delete",
  "role_update",
  "guild_update",
  "emoji_create",
  "emoji_delete",
  "emoji_update",
  "sticker_create",
  "sticker_delete",
  "sticker_update",
  "invite_create",
  "invite_delete",
  "webhook_update",
  // Voice
  "voice_join",
  "voice_leave",
  "voice_move",
  "voice_server_mute",
  "voice_server_deafen",
  "voice_self_mute",
  "voice_self_deafen",
  "voice_stream",
  "voice_video",
  // Moderation
  "case_create",
  "case_update",
  "case_delete",
  "case_expire",
  "case_warn",
  "case_note",
  "case_mute",
  "case_tempmute",
  "case_unmute",
  "case_kick",
  "case_ban",
  "case_tempban",
  "case_unban",
  "case_softban",
  "automod",
  "impersonation",
  "incident_response",
  "raid",
  "raid_mesh",
  "global_watchdog",
  "censor",
  "clean",
  "voice_mod",
  "dm_failed",
  "dreamcode_mod",
  "dreamcode_server",
  "passport_verify",
  "passport_kick",
  "economy_admin_change",
  // Tickets
  "ticket_open",
  "ticket_claim",
  "ticket_assign",
  "ticket_status",
  "ticket_close",
  // Suggestions
  "suggestion_create",
  "suggestion_approve",
  "suggestion_deny",
  "suggestion_comment",
  // Giveaways
  "giveaway_start",
  "giveaway_end",
  "giveaway_reroll",
  // Dashboard / website admin actions
  "dashboard_config",
  "dashboard_tag",
  "dashboard_command",
  "dashboard_suggestion",
  "dashboard_automod",
  "dashboard_impersonation",
  "dashboard_incident_response",
  "dashboard_chart",
  "dashboard_scam_protect",
  "dashboard_welcome",
  "dashboard_review",
  "dashboard_bot_brand",
  "dashboard_economy",
  "dashboard_ticket",
  "dashboard_giveaway",
  "dashboard_tts",
  "dashboard_permission_role",
  // Music
  "music_play",
  "music_skip",
  "music_stop",
  "music_playback",
  "music_queue",
  "music_filter",
  "music_dj",
  "music_playlist",
  "music_settings",
  "music_session",
  "music_error",
] as const;

export type LogEventType = (typeof LOG_EVENT_TYPES)[number];

export type LogEventCategory = "server" | "moderation";

export const LOG_EVENT_META: Record<
  LogEventType,
  { label: string; category: LogEventCategory; group: string }
> = {
  member_join: { label: "Member join", category: "server", group: "Members" },
  member_leave: { label: "Member leave", category: "server", group: "Members" },
  member_kick: { label: "Member kick", category: "server", group: "Members" },
  member_ban: { label: "Member ban", category: "server", group: "Members" },
  member_unban: { label: "Member unban", category: "server", group: "Members" },
  member_timeout: { label: "Timeout change", category: "server", group: "Members" },
  member_nick: { label: "Nickname change", category: "server", group: "Members" },
  member_roles: { label: "Role change", category: "server", group: "Members" },
  message_edit: { label: "Message edit", category: "server", group: "Messages" },
  message_delete: { label: "Message delete", category: "server", group: "Messages" },
  message_bulk_delete: { label: "Bulk delete", category: "server", group: "Messages" },
  message_pin: { label: "Message pin", category: "server", group: "Messages" },
  channel_create: { label: "Channel create", category: "server", group: "Channels" },
  channel_delete: { label: "Channel delete", category: "server", group: "Channels" },
  channel_update: { label: "Channel update", category: "server", group: "Channels" },
  thread_create: { label: "Thread create", category: "server", group: "Threads" },
  thread_update: { label: "Thread update", category: "server", group: "Threads" },
  thread_delete: { label: "Thread delete", category: "server", group: "Threads" },
  role_create: { label: "Role create", category: "server", group: "Roles" },
  role_delete: { label: "Role delete", category: "server", group: "Roles" },
  role_update: { label: "Role update", category: "server", group: "Roles" },
  guild_update: { label: "Server update", category: "server", group: "Server" },
  emoji_create: { label: "Emoji create", category: "server", group: "Emoji & stickers" },
  emoji_delete: { label: "Emoji delete", category: "server", group: "Emoji & stickers" },
  emoji_update: { label: "Emoji update", category: "server", group: "Emoji & stickers" },
  sticker_create: { label: "Sticker create", category: "server", group: "Emoji & stickers" },
  sticker_delete: { label: "Sticker delete", category: "server", group: "Emoji & stickers" },
  sticker_update: { label: "Sticker update", category: "server", group: "Emoji & stickers" },
  invite_create: { label: "Invite create", category: "server", group: "Invites" },
  invite_delete: { label: "Invite delete", category: "server", group: "Invites" },
  webhook_update: { label: "Webhook update", category: "server", group: "Server" },
  voice_join: { label: "Voice join", category: "server", group: "Voice" },
  voice_leave: { label: "Voice leave", category: "server", group: "Voice" },
  voice_move: { label: "Voice move", category: "server", group: "Voice" },
  voice_server_mute: { label: "Server mute", category: "server", group: "Voice" },
  voice_server_deafen: { label: "Server deafen", category: "server", group: "Voice" },
  voice_self_mute: { label: "Self mute", category: "server", group: "Voice" },
  voice_self_deafen: { label: "Self deafen", category: "server", group: "Voice" },
  voice_stream: { label: "Stream", category: "server", group: "Voice" },
  voice_video: { label: "Video", category: "server", group: "Voice" },
  case_create: { label: "Case create (legacy, generic)", category: "moderation", group: "Moderation" },
  case_update: { label: "Case update", category: "moderation", group: "Moderation" },
  case_delete: { label: "Case delete", category: "moderation", group: "Moderation" },
  case_expire: { label: "Case expire", category: "moderation", group: "Moderation" },
  case_warn: { label: "Warn", category: "moderation", group: "Moderation" },
  case_note: { label: "Note", category: "moderation", group: "Moderation" },
  case_mute: { label: "Mute", category: "moderation", group: "Moderation" },
  case_tempmute: { label: "Temp mute", category: "moderation", group: "Moderation" },
  case_unmute: { label: "Unmute", category: "moderation", group: "Moderation" },
  case_kick: { label: "Kick", category: "moderation", group: "Moderation" },
  case_ban: { label: "Ban", category: "moderation", group: "Moderation" },
  case_tempban: { label: "Temp ban", category: "moderation", group: "Moderation" },
  case_unban: { label: "Unban", category: "moderation", group: "Moderation" },
  case_softban: { label: "Softban", category: "moderation", group: "Moderation" },
  automod: { label: "Automod", category: "moderation", group: "Moderation" },
  impersonation: { label: "Impersonation Detection", category: "moderation", group: "Moderation" },
  incident_response: { label: "Incident Response", category: "moderation", group: "Moderation" },
  raid: { label: "Raid", category: "moderation", group: "Moderation" },
  raid_mesh: { label: "Raid Defense Mesh alert", category: "moderation", group: "Moderation" },
  global_watchdog: { label: "Global Watchdog hit", category: "moderation", group: "Moderation" },
  censor: { label: "Automod (legacy censor)", category: "moderation", group: "Moderation" },
  clean: { label: "Clean", category: "moderation", group: "Moderation" },
  voice_mod: { label: "Voice mod action", category: "moderation", group: "Moderation" },
  dm_failed: { label: "DM failed", category: "moderation", group: "Moderation" },
  dreamcode_mod: { label: "Custom command mod log", category: "moderation", group: "Moderation" },
  dreamcode_server: { label: "Custom command server log", category: "server", group: "Server" },
  passport_verify: { label: "Passport verify", category: "moderation", group: "Passport" },
  passport_kick: { label: "Passport kick", category: "moderation", group: "Passport" },
  economy_admin_change: { label: "Economy settings change", category: "server", group: "Economy" },
  ticket_open: { label: "Ticket opened", category: "moderation", group: "Tickets" },
  ticket_claim: { label: "Ticket claimed", category: "moderation", group: "Tickets" },
  ticket_assign: { label: "Ticket assigned", category: "moderation", group: "Tickets" },
  ticket_status: { label: "Ticket status changed", category: "moderation", group: "Tickets" },
  ticket_close: { label: "Ticket closed", category: "moderation", group: "Tickets" },
  suggestion_create: { label: "Suggestion created", category: "server", group: "Suggestions" },
  suggestion_approve: { label: "Suggestion approved", category: "moderation", group: "Suggestions" },
  suggestion_deny: { label: "Suggestion denied", category: "moderation", group: "Suggestions" },
  suggestion_comment: { label: "Suggestion comment", category: "server", group: "Suggestions" },
  giveaway_start: { label: "Giveaway started", category: "server", group: "Giveaways" },
  giveaway_end: { label: "Giveaway ended", category: "moderation", group: "Giveaways" },
  giveaway_reroll: { label: "Giveaway rerolled", category: "moderation", group: "Giveaways" },
  dashboard_config: { label: "Config update", category: "server", group: "Dashboard" },
  dashboard_tag: { label: "Tag change", category: "server", group: "Dashboard" },
  dashboard_command: { label: "Dream command change", category: "server", group: "Dashboard" },
  dashboard_suggestion: { label: "Suggestion admin", category: "moderation", group: "Dashboard" },
  dashboard_automod: { label: "Automod update", category: "moderation", group: "Dashboard" },
  dashboard_impersonation: { label: "Impersonation Detection update", category: "moderation", group: "Dashboard" },
  dashboard_incident_response: { label: "Incident Response update", category: "moderation", group: "Dashboard" },
  dashboard_chart: { label: "Custom chart", category: "server", group: "Dashboard" },
  dashboard_scam_protect: { label: "Scam protect", category: "moderation", group: "Dashboard" },
  dashboard_welcome: { label: "Welcomer asset", category: "server", group: "Dashboard" },
  dashboard_review: { label: "Review admin", category: "server", group: "Dashboard" },
  dashboard_bot_brand: { label: "Bot brand", category: "server", group: "Dashboard" },
  dashboard_economy: { label: "Economy change", category: "server", group: "Dashboard" },
  dashboard_ticket: { label: "Ticket admin", category: "moderation", group: "Dashboard" },
  dashboard_giveaway: { label: "Giveaway admin", category: "moderation", group: "Dashboard" },
  dashboard_tts: { label: "TTS admin", category: "moderation", group: "Dashboard" },
  dashboard_permission_role: { label: "Dreamliner Role change", category: "server", group: "Dashboard" },
  music_play: { label: "Track played/queued", category: "server", group: "Music" },
  music_skip: { label: "Track skipped", category: "server", group: "Music" },
  music_stop: { label: "Playback stopped", category: "server", group: "Music" },
  music_playback: { label: "Playback control (pause/resume/volume/seek)", category: "server", group: "Music" },
  music_queue: { label: "Queue changed", category: "server", group: "Music" },
  music_filter: { label: "Audio filter changed", category: "server", group: "Music" },
  music_dj: { label: "DJ settings changed", category: "server", group: "Music" },
  music_playlist: { label: "Playlist changed", category: "server", group: "Music" },
  music_settings: { label: "Music settings changed", category: "server", group: "Music" },
  music_session: { label: "Voice session (join, resume, reconnect)", category: "server", group: "Music" },
  music_error: { label: "Playback error", category: "server", group: "Music" },
};

export function isLogEventType(value: string): value is LogEventType {
  return (LOG_EVENT_TYPES as readonly string[]).includes(value);
}

export function defaultLoggingEvents(): Record<LogEventType, boolean> {
  return Object.fromEntries(LOG_EVENT_TYPES.map((key) => [key, true])) as Record<LogEventType, boolean>;
}

export function getLoggingEventGroups(): Array<{
  group: string;
  events: Array<{ key: LogEventType; label: string; category: LogEventCategory }>;
}> {
  const map = new Map<string, Array<{ key: LogEventType; label: string; category: LogEventCategory }>>();
  for (const key of LOG_EVENT_TYPES) {
    const meta = LOG_EVENT_META[key];
    const list = map.get(meta.group) ?? [];
    list.push({ key, label: meta.label, category: meta.category });
    map.set(meta.group, list);
  }
  return [...map.entries()].map(([group, events]) => ({ group, events }));
}
