import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkgPath = join(root, "package.json");
const lockPath = join(root, "package-lock.json");

const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as { version: string };
const parts = pkg.version.split(".").map((part) => Number.parseInt(part, 10));
parts[2] = (parts[2] ?? 0) + 1;
const newVersion = parts.join(".");

pkg.version = newVersion;
writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

try {
  const lock = JSON.parse(readFileSync(lockPath, "utf-8")) as {
    version?: string;
    packages?: Record<string, { version?: string }>;
  };
  lock.version = newVersion;
  if (lock.packages?.[""]) lock.packages[""].version = newVersion;
  writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
} catch {
  // package-lock.json may be absent in some environments
}

const builtAt = new Date().toISOString();
const genDir = join(root, "src", "generated");
mkdirSync(genDir, { recursive: true });
writeFileSync(
  join(genDir, "version.ts"),
  `// Auto-generated by scripts/bump-version.ts — do not edit
export const BUILD_VERSION = ${JSON.stringify(newVersion)};
export const BUILD_TIME = ${JSON.stringify(builtAt)};
`,
);

console.log(`Version bumped to ${newVersion}`);
