import { z } from "zod";
import { boolPerm, channelId } from "../schemaHelp.js";
import { zPluginSection } from "./pluginSection.js";
import {
  WELCOME_MILESTONE_MESSAGE_MODES,
  zWelcomeCardConfig,
  zWelcomeEmbedConfig,
  zWelcomeRichMessage,
} from "./welcome.js";

export const ACTIVITY_METRICS = ["messages", "voice_minutes"] as const;
export type ActivityMetric = (typeof ACTIVITY_METRICS)[number];

/** Where the shared announcement goes: a fixed channel, the channel the member was active in
 *  (their message's channel, or their voice channel's built-in text chat), or their DMs. */
export const ACTIVITY_ANNOUNCE_DESTINATIONS = ["channel", "current", "dm"] as const;

export const MAX_ACTIVITY_MILESTONES = 50;

export const zActivityMilestone = z.strictObject({
  id: z.number().int().positive().describe("Stable milestone ID. Generated by the dashboard, do not edit by hand."),
  enabled: z.boolean().default(true).describe("Turn this milestone on or off without deleting it."),
  name: z
    .string()
    .max(80)
    .default("")
    .describe("Optional label, shown as {milestone}. Defaults to the requirement, e.g. \"1,000 messages\"."),
  metric: z
    .enum(ACTIVITY_METRICS)
    .default("messages")
    .describe("What members progress towards: messages sent, or minutes spent in voice."),
  threshold: z
    .number()
    .int()
    .min(1)
    .max(100_000_000)
    .default(100)
    .describe("Messages (or voice minutes) needed to reach this milestone."),
  roles: z.array(z.string()).max(10).default([]).describe("Roles granted when a member reaches this milestone."),
  remove_roles: z
    .array(z.string())
    .max(10)
    .default([])
    .describe("Roles taken away when a member reaches this milestone, e.g. a starter role."),
  announce: z.boolean().default(true).describe("Post an announcement when a member reaches this milestone."),
  channel_id: channelId("Optional channel for this milestone only. Leave empty to use the default destination."),
  message_mode: z
    .enum(WELCOME_MILESTONE_MESSAGE_MODES)
    .default("default")
    .describe("default = post the shared announcement, custom = post this milestone's own message."),
  message: zWelcomeRichMessage.default({}).describe("This milestone's own message, used when message_mode is custom."),
});

export const zActivityAnnouncement = z.strictObject({
  enabled: z.boolean().default(true).describe("Announce milestones by default. Each milestone can override this."),
  destination: z
    .enum(ACTIVITY_ANNOUNCE_DESTINATIONS)
    .default("current")
    .describe(
      "channel = always post in the channel below, current = post where the member was active (falls back to the channel below), dm = message the member privately.",
    ),
  channel_id: channelId("Announcement channel (and the fallback for the 'current' destination)."),
  content: z
    .string()
    .max(2000)
    .default("🎉 {user} just reached **{milestone}**!")
    .describe(
      "Default announcement. Supports placeholders plus {milestone}, {milestone_requirement}, {messages}, {voice_time}, {voice_hours}, {reward_roles} and {next_milestone}.",
    ),
  embed: zWelcomeEmbedConfig.default({}),
  card: zWelcomeCardConfig.default({
    greeting_text: "Milestone unlocked!",
    subtitle_text: "{user_display} reached {milestone}",
  }),
});

export const zActivityRewardsConfig = z.strictObject({
  stacking: z
    .boolean()
    .default(true)
    .describe(
      "If true (default), members keep every milestone role they've earned. If false, only the highest milestone role per track (messages, voice) is kept.",
    ),
  milestones: z
    .array(zActivityMilestone)
    .max(MAX_ACTIVITY_MILESTONES)
    .default([])
    .describe("Message and voice milestones, each with its own rewards and optional announcement override."),
  announcement: zActivityAnnouncement.default({}),
  message_cooldown_seconds: z
    .number()
    .int()
    .min(0)
    .max(3600)
    .default(30)
    .describe("Only one message per member counts in this window, so spam doesn't race people up the ladder. 0 counts every message."),
  min_message_length: z
    .number()
    .int()
    .min(0)
    .max(2000)
    .default(0)
    .describe("Ignore messages shorter than this many characters (attachments-only messages always count)."),
  ignored_channels: z
    .array(z.string())
    .default([])
    .describe("Channels (text or voice, or their categories) where activity never counts."),
  ignored_roles: z.array(z.string()).default([]).describe("Members with any of these roles never progress."),
  voice_require_others: z
    .boolean()
    .default(true)
    .describe("Only count voice time while at least one other person is in the channel."),
  voice_ignore_muted: z
    .boolean()
    .default(true)
    .describe("Don't count voice time while a member is muted or deafened."),
  voice_ignore_afk: z.boolean().default(true).describe("Don't count time spent in the server's AFK channel."),
  can_view: boolPerm("view milestones, their own progress and the leaderboard with /rewards"),
  can_sync: boolPerm("re-sync their own milestone roles with /rewards sync"),
  can_manage: boolPerm("adjust or reset a member's progress with /rewards adjust and /rewards reset"),
});

export type ActivityMilestone = z.infer<typeof zActivityMilestone>;
export type ActivityAnnouncement = z.infer<typeof zActivityAnnouncement>;
export type ActivityRewardsConfig = z.infer<typeof zActivityRewardsConfig>;

export const zActivityRewardsPluginSection = zPluginSection(zActivityRewardsConfig.shape);
