import { z } from "zod";
import { boolPerm, channelId } from "../schemaHelp.js";
import { zPluginSection } from "./pluginSection.js";
import { TICKET_BUTTON_STYLES, zTicketFormQuestion } from "./tickets.js";
import { zWelcomeEmbedConfig } from "./welcome.js";

/**
 * Dreamliner's own application emojis used across Applications (see app-emojis.txt). App emojis
 * render in every server and in DMs, so these work regardless of which server the bot is in.
 */
export const APPLICATION_EMOJIS = {
  /** Default apply-button emoji for new openings. */
  apply: "<:icons_pen:1544417369709871224>",
  pending: "<:icons_hoursglass:1544417711864549479>",
  accepted: "<:icons_Correct:1544417199798886530>",
  denied: "<:icons_Wrong:1544417460638457937>",
  next: "<:icons_rightarrow:1544417401180000337>",
  submitted: "<:icons_envelope:1544417793007681566>",
  pageSaved: "<:icons_todolist:1544417596307279952>",
  celebrate: "<:icons_tada:1544417975472492594>",
} as const;

/** Four modal pages of five questions each. Longer forms are asked page by page. */
export const MAX_APPLICATION_QUESTIONS = 20;
export const MAX_APPLICATION_OPENINGS = 25;

export const APPLICATION_STATUSES = ["pending", "accepted", "denied"] as const;
export type ApplicationStatus = (typeof APPLICATION_STATUSES)[number];

/** The opening's post: plain text plus the welcomer-style embed. */
export const zApplicationPostMessage = z.strictObject({
  content: z.string().max(2000).default("").describe("Optional text above the embed. Supports placeholders."),
  embed: zWelcomeEmbedConfig.default({
    enabled: true,
    title: "{opening} applications are open",
    description: "Think you'd be a great fit? Hit the button below to apply.",
    thumbnail: "guild",
  }),
});

export const zApplicationButton = z.strictObject({
  label: z.string().max(80).default("Apply").describe("Text on the apply button."),
  emoji: z.string().max(128).default(APPLICATION_EMOJIS.apply).describe("Button emoji (unicode, emoji id, or <:name:id>)."),
  style: z.enum(TICKET_BUTTON_STYLES).default("primary").describe("Button color."),
});

export const zApplicationOpening = z.strictObject({
  id: z.string().uuid().describe("Stable opening ID. Generated by the dashboard, do not edit by hand."),
  enabled: z.boolean().default(true).describe("Turn this opening off without deleting it. Its button stops working."),
  accepting: z
    .boolean()
    .default(true)
    .describe("Whether new applications are accepted. Turn off to pause an opening without taking the post down."),
  name: z.string().max(80).default("").describe("What members are applying for, e.g. Moderator. Shown as {opening}."),
  description: z.string().max(200).default("").describe("Short dashboard description, shown as {opening_description}."),

  channel_id: channelId("Channel the opening's post (with its apply button) is published in."),
  message_id: z
    .string()
    .optional()
    .describe("ID of the published post. Set automatically when the bot publishes this opening."),
  message: zApplicationPostMessage.default({}),
  button: zApplicationButton.default({}),

  modal_title: z
    .string()
    .max(45)
    .default("")
    .describe("Title of the application form. Defaults to \"<opening> application\"."),
  questions: z
    .array(zTicketFormQuestion)
    .max(MAX_APPLICATION_QUESTIONS)
    .default([])
    .describe(`Up to ${MAX_APPLICATION_QUESTIONS} questions. Every 5 become one page of the form.`),

  review_channel_id: channelId("Where this opening's applications go. Leave empty to use the default review channel."),
  ping_roles: z.array(z.string()).max(10).default([]).describe("Roles pinged when a new application arrives."),
  review_thread: z
    .boolean()
    .default(false)
    .describe("Start a thread on each application so reviewers can discuss it."),

  required_roles: z.array(z.string()).default([]).describe("Members need at least one of these roles to apply."),
  blocked_roles: z.array(z.string()).default([]).describe("Members with any of these roles can't apply."),
  min_account_age_days: z
    .number()
    .int()
    .min(0)
    .max(3650)
    .default(0)
    .describe("Minimum Discord account age in days (0 = no minimum)."),
  min_member_days: z
    .number()
    .int()
    .min(0)
    .max(3650)
    .default(0)
    .describe("Minimum days in this server before applying (0 = no minimum)."),
  cooldown_days: z
    .number()
    .int()
    .min(0)
    .max(365)
    .default(7)
    .describe("Days a denied applicant waits before applying again (0 = right away)."),

  accept_roles: z.array(z.string()).max(10).default([]).describe("Roles granted when an application is accepted."),
  accept_remove_roles: z
    .array(z.string())
    .max(10)
    .default([])
    .describe("Roles removed when an application is accepted, e.g. a trial role."),
  dm_decision: z.boolean().default(true).describe("DM the applicant when their application is accepted or denied."),
  accept_message: z
    .string()
    .max(2000)
    .default(`${APPLICATION_EMOJIS.celebrate} Your application for **{opening}** in **{guild}** was accepted. Welcome aboard!`)
    .describe("DM sent on acceptance. Supports {user}, {opening}, {guild} and {reason}."),
  deny_message: z
    .string()
    .max(2000)
    .default("Thanks for applying for **{opening}** in **{guild}**. Unfortunately it wasn't accepted this time.")
    .describe("DM sent on denial. Supports {user}, {opening}, {guild} and {reason}. A reason is added below it if the template doesn't use {reason}."),
});

export const zApplicationsConfig = z.strictObject({
  review_channel_id: channelId("Default channel new applications are sent to for review."),
  openings: z
    .array(zApplicationOpening)
    .max(MAX_APPLICATION_OPENINGS)
    .default([])
    .describe("Roles or positions members can apply for, each with its own post, form, and review settings."),
  can_review: boolPerm("accept or deny applications from the review channel"),
});

export const zApplicationsPluginSection = zPluginSection(zApplicationsConfig.shape);

export type ApplicationOpening = z.infer<typeof zApplicationOpening>;
export type ApplicationsConfig = z.infer<typeof zApplicationsConfig>;
