import { z } from "zod";
import { boolPerm } from "../schemaHelp.js";

export const COUNTING_RESET_TARGETS = ["zero", "last_milestone"] as const;
export type CountingResetTarget = (typeof COUNTING_RESET_TARGETS)[number];

export const zCountingChannel = z
  .strictObject({
    id: z.string().uuid().describe("Stable channel setup ID. Generated by the dashboard, do not edit by hand."),
    name: z.string().max(80).default("").describe("Dashboard-only label for this counting channel."),
    enabled: z.boolean().default(true).describe("Turn counting on or off in this channel without deleting the setup."),
    channel_id: z.string().min(1).describe("Text channel members count in."),
    start_at: z
      .number()
      .int()
      .min(0)
      .max(2_147_483_647)
      .default(1)
      .describe("The first number of the count."),
    step: z
      .number()
      .int()
      .min(1)
      .max(1000)
      .default(1)
      .describe("How much the count must go up by each time, e.g. 2 for counting by twos."),
    allow_math: z
      .boolean()
      .default(false)
      .describe("Allow simple arithmetic (e.g. \"12+3\") as long as it evaluates to the right number."),
    require_alternate_user: z
      .boolean()
      .default(true)
      .describe("The same member can't post two counts in a row, someone else must count in between."),
    cooldown_seconds: z
      .number()
      .int()
      .min(0)
      .max(3600)
      .default(0)
      .describe("Minimum seconds between any two successful counts in this channel. 0 disables the cooldown."),
    allow_bots: z.boolean().default(false).describe("Let bot accounts participate in the count."),
    allow_non_number_messages: z
      .boolean()
      .default(false)
      .describe(
        "When on, messages that aren't a counting attempt (not a plain number, or a math expression if allowed) are left alone. When off (default), every message in the channel is judged, and anything that isn't the right number breaks the count.",
      ),
    delete_wrong_messages: z
      .boolean()
      .default(true)
      .describe("Delete messages that break the count (wrong number, out of turn, or on cooldown)."),
    reset_on_mistake: z
      .boolean()
      .default(true)
      .describe("Reset the count back down when someone breaks it. Turn off for a lenient/practice channel."),
    reset_to: z
      .enum(COUNTING_RESET_TARGETS)
      .default("zero")
      .describe(
        "Where the count resets to on a mistake: back to zero, or back down to the last milestone reached (see milestone_every).",
      ),
    milestone_every: z
      .number()
      .int()
      .min(0)
      .max(1_000_000)
      .default(0)
      .describe("Celebrate every Nth count (e.g. 100). 0 disables milestones."),
    announce_milestones: z
      .boolean()
      .default(true)
      .describe("Post milestone_message when a milestone count is reached."),
    pin_milestones: z.boolean().default(false).describe("Pin the message that hits a milestone count."),
    announce_new_record: z
      .boolean()
      .default(true)
      .describe("Post a message when the count climbs past this channel's previous highest count."),
    announce_failure: z
      .boolean()
      .default(true)
      .describe("Post failure_message when someone breaks the count."),
    success_reaction: z
      .string()
      .max(128)
      .default("<:icons_Correct:1544417199798886530>")
      .describe("Emoji reacted to a correct count. Leave empty for no reaction."),
    failure_reaction: z
      .string()
      .max(128)
      .default("<:icons_Wrong:1544417460638457937>")
      .describe("Emoji reacted to a message that breaks the count. Leave empty for no reaction."),
    milestone_reaction: z
      .string()
      .max(128)
      .default("<:icons_tada:1544417975472492594>")
      .describe("Extra emoji reacted to a milestone count, alongside success_reaction. Leave empty for none."),
    failure_message: z
      .string()
      .max(300)
      .default("{user} broke the count! {reason} Starting over from **{restart}**.")
      .describe(
        "Message posted when someone breaks the count. Placeholders: {user}, {reason} (what went wrong, e.g. \"You can't count twice in a row.\"), {number} (what they posted, if numeric), {expected}, {restart} (the count after resetting), {highest}.",
      ),
    milestone_message: z
      .string()
      .max(300)
      .default("{user} just hit **{number}**!")
      .describe("Message posted on a milestone count. Placeholders: {user}, {number}, {highest}."),
    record_message: z
      .string()
      .max(300)
      .default("{user} broke the record! New highest count: **{number}**.")
      .describe("Message posted when a new record is set. Placeholders: {user}, {number}, {highest}."),
    ignored_roles: z
      .array(z.string())
      .default([])
      .describe(
        "Members with any of these roles can't count here. Their attempts are removed (if delete_wrong_messages is on) and never affect the count either way.",
      ),
    allowed_roles: z
      .array(z.string())
      .default([])
      .describe(
        "If set, only members with one of these roles can count here. Everyone else is treated the same as ignored_roles. Leave empty to allow everyone.",
      ),
    use_webhook: z
      .boolean()
      .default(false)
      .describe(
        "Post success/milestone/failure/record messages as a webhook with a custom name and avatar instead of the bot. Requires Manage Webhooks. Falls back to the bot if a webhook cannot be created.",
      ),
    webhook_name: z
      .string()
      .max(80)
      .default("")
      .describe("Webhook display name. Defaults to this setup's name, then \"Counting\"."),
    webhook_avatar_url: z
      .string()
      .max(512)
      .default("")
      .describe("Webhook avatar image URL (https)."),
  })
  .superRefine((channel, ctx) => {
    if (channel.reset_to === "last_milestone" && channel.milestone_every <= 0) {
      ctx.addIssue({
        code: "custom",
        message: "reset_to \"last_milestone\" requires milestone_every to be set above 0.",
        path: ["reset_to"],
      });
    }
  });

export const zCountingConfig = z.strictObject({
  can_reset: boolPerm("manually reset a counting channel's count"),
  can_stats: boolPerm("check a counting channel's current count and record"),
  channels: z.array(zCountingChannel).default([]).describe("Counting channels for this server."),
});

export type CountingChannel = z.infer<typeof zCountingChannel>;
export type CountingConfig = z.infer<typeof zCountingConfig>;
