import { z } from "zod";
import { boolPerm } from "../schemaHelp.js";
import { zPluginSection } from "./pluginSection.js";

/** Each maps to one free, keyless API, see plugins/images/functions/sources.ts. */
export const IMAGE_SOURCES = ["anime", "blahaj", "cat", "dog", "fox", "duck", "capybara", "bird"] as const;
export type ImageSource = (typeof IMAGE_SOURCES)[number];

export const MAX_IMAGE_DAILY_SENDS = 10;

export function isValidTimeZone(value: string): boolean {
  try {
    new Intl.DateTimeFormat("en-US", { timeZone: value });
    return true;
  } catch {
    return false;
  }
}

export const zImageDailySend = z.strictObject({
  id: z.number().int().positive().describe("Stable daily send ID. Generated by the dashboard, do not edit by hand."),
  enabled: z.boolean().default(true).describe("Turn this daily send on or off without deleting it."),
  channel_id: z
    .string()
    .default("")
    .describe("Text channel the daily image is posted in. Nothing is posted until one is set."),
  source: z.enum(IMAGE_SOURCES).default("anime").describe(
      "Which image API to pull from: anime (nekos.best), blahaj (transgirl.wamellow.com), cat (TheCatAPI), " +
        "dog (Dog CEO), fox (RandomFox), duck (random-d.uk), capybara (capy.lol), or bird (AlexFlipnote).",
    ),
  time: z
    .string()
    .regex(/^([01]\d|2[0-3]):[0-5]\d$/, "Time must be HH:MM (24-hour).")
    .default("12:00")
    .describe("Time of day to post, as 24-hour HH:MM in the chosen timezone."),
  timezone: z
    .string()
    .refine(isValidTimeZone, "Unknown timezone.")
    .default("UTC")
    .describe("IANA timezone the time is in, e.g. Europe/London or America/New_York."),
});

export const zImagesConfig = z.strictObject({
  can_use: boolPerm("use /image"),
  daily: z
    .array(zImageDailySend)
    .max(MAX_IMAGE_DAILY_SENDS)
    .default([])
    .describe(`Daily image sends (max ${MAX_IMAGE_DAILY_SENDS}). Each one posts a fresh image into its channel once a day.`),
});

export const zImagesPluginSection = zPluginSection(zImagesConfig.shape);

export type ImagesConfig = z.infer<typeof zImagesConfig>;
export type ImageDailySend = z.infer<typeof zImageDailySend>;
