import { z } from "zod";
import { boolPerm } from "../schemaHelp.js";
import { zPersistEmbedConfig } from "./persist.js";

export const zRolePanelRole = z.strictObject({
  role_id: z.string().min(1).describe("Role ID to grant/revoke."),
  emoji: z
    .string()
    .max(128)
    .default("")
    .describe("Unicode or <:name:id> emoji. Required for reaction-trigger panels; optional decoration for button-trigger panels."),
  label: z
    .string()
    .max(80)
    .default("")
    .describe("Button label (button trigger only). Leave empty to use the role's live name."),
  style: z
    .enum(["primary", "secondary", "success", "danger"])
    .default("secondary")
    .describe("Button color (button trigger only)."),
});

export const zRolePanel = z
  .strictObject({
    id: z.string().uuid().describe("Stable panel ID. Generated by the dashboard, do not edit by hand."),
    name: z.string().max(80).default("").describe("Dashboard-only label for this panel."),
    enabled: z.boolean().default(true).describe("Turn this panel on or off without deleting it."),
    trigger_type: z
      .enum(["reaction", "button"])
      .describe("How members claim a role: reacting to the message, or clicking a button."),
    post_mode: z
      .enum(["bot", "existing"])
      .describe("\"bot\" posts and owns a message with full embed/content control. \"existing\" attaches reactions/a button row to a message you already posted, leaving its content untouched."),
    selection_mode: z
      .enum(["multiple", "single"])
      .default("multiple")
      .describe("\"single\" removes any other role from this panel the member already has when they pick a new one."),
    remove_on_unreact: z
      .boolean()
      .default(true)
      .describe("Reaction trigger only: remove the role when the member removes their reaction."),
    channel_id: z.string().default("").describe("Channel to post in. Required when post_mode is bot."),
    existing_message_link: z
      .string()
      .default("")
      .describe("Link to the message to attach roles to. Required when post_mode is existing."),
    content: z.string().max(2000).default("").describe("Message text. Only used when post_mode is bot."),
    embed: zPersistEmbedConfig.default({}).describe("Optional Discord embed. Only used when post_mode is bot."),
    roles: z
      .array(zRolePanelRole)
      .min(1, "Add at least one role.")
      .max(25, "A panel supports at most 25 roles.")
      .describe("The roles members can claim on this panel."),
  })
  .superRefine((panel, ctx) => {
    if (panel.trigger_type === "reaction" && panel.roles.length > 20) {
      ctx.addIssue({ code: "custom", message: "Reaction panels support at most 20 roles.", path: ["roles"] });
    }
    if (panel.trigger_type === "reaction" && panel.roles.some((r) => !r.emoji.trim())) {
      ctx.addIssue({ code: "custom", message: "Every role needs an emoji for a reaction panel.", path: ["roles"] });
    }
    if (panel.post_mode === "bot" && !panel.channel_id.trim()) {
      ctx.addIssue({ code: "custom", message: "channel_id is required when post_mode is bot.", path: ["channel_id"] });
    }
    if (panel.post_mode === "existing" && !panel.existing_message_link.trim()) {
      ctx.addIssue({
        code: "custom",
        message: "existing_message_link is required when post_mode is existing.",
        path: ["existing_message_link"],
      });
    }
  });

export const zRolePanelsConfig = z.strictObject({
  can_manage: boolPerm("manage role panels").describe(
    "Vestigial. Dashboard routes gate on Discord Manage Server, not this flag. Kept for /permissions consistency.",
  ),
  panels: z.array(zRolePanel).default([]).describe("Role panels for this server."),
});

export type RolePanelRole = z.infer<typeof zRolePanelRole>;
export type RolePanel = z.infer<typeof zRolePanel>;
export type RolePanelsConfig = z.infer<typeof zRolePanelsConfig>;
