import { z } from "zod";
import { boolPerm, channelId, roleId } from "../schemaHelp.js";
import { zPluginOverride } from "./pluginSection.js";
import { zPersistEmbedConfig } from "./persist.js";

/** Discord modal text inputs max out at 5 per modal. */
export const MAX_FORM_QUESTIONS = 5;

export const TICKET_CONTAINER_MODES = ["channel", "thread"] as const;
export type TicketContainerMode = (typeof TICKET_CONTAINER_MODES)[number];

export const TICKET_PANEL_STYLES = ["buttons", "select"] as const;
export type TicketPanelStyle = (typeof TICKET_PANEL_STYLES)[number];

export const TICKET_BUTTON_STYLES = ["primary", "secondary", "success", "danger"] as const;
export type TicketButtonStyle = (typeof TICKET_BUTTON_STYLES)[number];

export const TICKET_CLOSE_PERMISSIONS = ["opener", "staff", "either"] as const;
export type TicketClosePermission = (typeof TICKET_CLOSE_PERMISSIONS)[number];

export const TICKET_PRIORITIES = ["low", "medium", "high", "urgent"] as const;
export type TicketPriority = (typeof TICKET_PRIORITIES)[number];

export const zTicketFormQuestion = z
  .strictObject({
    id: z.string().uuid().describe("Stable question ID. Generated by the dashboard, do not edit by hand."),
    label: z.string().max(45).default("").describe("Modal field label (Discord limit: 45 characters)."),
    style: z
      .enum(["short", "paragraph"])
      .default("short")
      .describe("Short is a single line, paragraph is a multi-line box."),
    required: z.boolean().default(true).describe("Block ticket creation until this question is answered."),
    placeholder: z.string().max(100).default("").describe("Optional placeholder text shown in the empty field."),
    max_length: z
      .number()
      .int()
      .min(1)
      .max(4000)
      .default(1000)
      .describe("Maximum answer length."),
  })
  .superRefine((question, ctx) => {
    if (!question.label.trim()) {
      ctx.addIssue({ code: "custom", message: "Give this question a label.", path: ["label"] });
    }
  });

export const TICKET_ESCALATION_ACTIONS = ["ping_role", "notify_channel", "set_priority", "close"] as const;
export type TicketEscalationAction = (typeof TICKET_ESCALATION_ACTIONS)[number];

export const zTicketEscalationStep = z
  .strictObject({
    id: z.string().uuid().describe("Stable step ID. Generated by the dashboard, do not edit by hand."),
    after_minutes: z
      .number()
      .int()
      .min(1)
      .describe("Trigger this step after this many minutes without a staff reply (or since the ticket opened, if staff never replied)."),
    action: z
      .enum(TICKET_ESCALATION_ACTIONS)
      .describe("ping_role: mention a role in the ticket. notify_channel: post an alert to another channel. set_priority: bump the ticket's priority. close: auto-close the ticket."),
    role_id: roleId("Role to ping in the ticket channel. Only used by ping_role."),
    channel_id: channelId("Channel to post the alert to. Only used by notify_channel."),
    priority: z.enum(TICKET_PRIORITIES).optional().describe("Priority to set. Only used by set_priority."),
    message: z.string().max(500).default("").describe("Optional note appended to the ping/alert."),
  })
  .superRefine((step, ctx) => {
    if (step.action === "ping_role" && !step.role_id) {
      ctx.addIssue({ code: "custom", message: "role_id is required for ping_role steps.", path: ["role_id"] });
    }
    if (step.action === "notify_channel" && !step.channel_id) {
      ctx.addIssue({ code: "custom", message: "channel_id is required for notify_channel steps.", path: ["channel_id"] });
    }
    if (step.action === "set_priority" && !step.priority) {
      ctx.addIssue({ code: "custom", message: "priority is required for set_priority steps.", path: ["priority"] });
    }
  });

export type TicketEscalationStep = z.infer<typeof zTicketEscalationStep>;

export const zTicketCategory = z
  .strictObject({
    id: z.string().uuid().describe("Stable category ID. Generated by the dashboard, do not edit by hand."),
    label: z.string().max(80).default("").describe("Shown on the button or in the select menu."),
    description: z
      .string()
      .max(100)
      .default("")
      .describe("Short description. Select-menu panels only."),
    emoji: z.string().max(128).default("").describe("Unicode or <:name:id> emoji for the button/option."),
    button_style: z
      .enum(TICKET_BUTTON_STYLES)
      .default("primary")
      .describe("Button color. Only used when the panel's style is buttons."),
    category_channel_id: channelId("Discord channel category ticket channels are created under."),
    mode: z
      .enum(TICKET_CONTAINER_MODES)
      .default("channel")
      .describe("Open tickets as a private channel or a private thread."),
    naming_pattern: z
      .string()
      .max(80)
      .default("ticket-{number}")
      .describe("Channel/thread name pattern. Supports {number}, {username}, {category}."),
    welcome_message: z
      .string()
      .max(2000)
      .default(
        "Thanks for reaching out, {user}! Support will be with you shortly.",
      )
      .describe("Message posted in the new ticket. Supports {user}, {guild}, {category}, plus each question's answer as {answer_1}, {answer_2}, ..."),
    support_role_ids: z
      .array(z.string())
      .default([])
      .describe("Roles that can see and reply in tickets from this category. Falls back to the plugin-wide staff roles when empty."),
    ping_role_ids: z
      .array(z.string())
      .default([])
      .describe("Roles pinged (then message deleted) when a new ticket in this category opens."),
    form_questions: z
      .array(zTicketFormQuestion)
      .max(MAX_FORM_QUESTIONS)
      .default([])
      .describe("Up to 5 questions asked in a modal before the ticket opens."),
    max_open_per_user: z
      .number()
      .int()
      .min(0)
      .optional()
      .describe("Per-user open-ticket limit for this category. 0 disables new tickets. Leave empty to use the plugin-wide limit."),
    auto_close_hours: z
      .number()
      .min(0)
      .default(0)
      .describe("Auto-close the ticket after this many hours of opener inactivity. 0 disables auto-close."),
    escalation: z
      .array(zTicketEscalationStep)
      .max(10)
      .default([])
      .describe(
        "SLA ladder: steps fire in order based on minutes of staff silence (no staff reply since the ticket opened, or since their last reply). Re-arms whenever staff replies again.",
      ),
    close_permission: z
      .enum(TICKET_CLOSE_PERMISSIONS)
      .default("either")
      .describe("Who may close tickets from this category: the opener, staff only, or either."),
    require_close_reason: z.boolean().default(false).describe("Require a reason when closing a ticket."),
    transcript_channel_id: channelId("Transcript log channel override for this category. Falls back to the plugin-wide transcript channel."),
    feedback_enabled: z
      .boolean()
      .optional()
      .describe("DM the opener a rating request when their ticket closes. Leave empty to use the plugin-wide setting."),
  })
  .superRefine((category, ctx) => {
    if (!category.label.trim()) {
      ctx.addIssue({ code: "custom", message: "Give this category a label.", path: ["label"] });
    }
    if (!category.category_channel_id) {
      ctx.addIssue({
        code: "custom",
        message: "category_channel_id is required so ticket channels have somewhere to be created.",
        path: ["category_channel_id"],
      });
    }
  });

export const zTicketPanel = z
  .strictObject({
    id: z.string().uuid().describe("Stable panel ID. Generated by the dashboard, do not edit by hand."),
    name: z.string().max(80).default("").describe("Dashboard-only label for this panel."),
    enabled: z.boolean().default(true).describe("Turn this panel on or off without deleting it."),
    channel_id: channelId("Channel this panel's message is posted in."),
    style: z
      .enum(TICKET_PANEL_STYLES)
      .default("buttons")
      .describe("Show each category as its own button (max 5) or as options in one select menu (max 25)."),
    content: z.string().max(2000).default("").describe("Optional message text above the embed."),
    embed: zPersistEmbedConfig.default({}).describe("The panel's embed. Supports {guild} placeholders."),
    categories: z
      .array(zTicketCategory)
      .min(1, "Add at least one category.")
      .max(25, "A panel supports at most 25 categories.")
      .default([]),
    message_id: z
      .string()
      .optional()
      .describe("ID of the currently-posted panel message. Set automatically when the bot posts/reposts this panel."),
  })
  .superRefine((panel, ctx) => {
    if (panel.style === "buttons" && panel.categories.length > 5) {
      ctx.addIssue({
        code: "custom",
        message: "Button-style panels support at most 5 categories. Switch to select-menu style for more.",
        path: ["categories"],
      });
    }
  });

export const zTicketsConfig = z.strictObject({
  staff_role_ids: z
    .array(z.string())
    .default([])
    .describe("Plugin-wide support staff roles. Used as the fallback when a category has no support_role_ids of its own."),
  log_channel_id: channelId("Channel for ticket open/claim/close event logs."),
  default_transcript_channel_id: channelId("Default channel transcripts are posted to when a category has no override."),
  dm_transcript_on_close: z.boolean().default(true).describe("DM the ticket opener their transcript when the ticket closes."),
  feedback_enabled: z.boolean().default(false).describe("Plugin-wide default: DM the opener a rating request after close."),
  max_open_tickets_per_user: z
    .number()
    .int()
    .min(1)
    .default(1)
    .describe("Plugin-wide default limit on how many tickets one member may have open at once."),
  blacklist_notify: z.boolean().default(true).describe("Tell blacklisted members why their ticket attempt was blocked."),
  panels: z.array(zTicketPanel).default([]).describe("Ticket panels for this server."),
  can_claim: boolPerm("claim tickets"),
  can_close: boolPerm("close their own tickets"),
  can_close_others: boolPerm("close tickets opened by other members"),
  can_reopen: boolPerm("reopen closed tickets"),
  can_add_remove_members: boolPerm("add or remove members from a ticket"),
  can_manage_panels: boolPerm("post, repost, and edit ticket panels"),
  can_view_all: boolPerm("view any ticket, not just ones they're part of"),
  can_delete: boolPerm("permanently delete tickets"),
  can_blacklist: boolPerm("blacklist members or roles from opening tickets"),
});

export type TicketFormQuestion = z.infer<typeof zTicketFormQuestion>;
export type TicketCategory = z.infer<typeof zTicketCategory>;
export type TicketPanel = z.infer<typeof zTicketPanel>;
export type TicketsConfig = z.infer<typeof zTicketsConfig>;

export const zTicketsPluginSection = z.strictObject({
  enabled: z.boolean().optional().describe("Turn tickets on or off for this server."),
  config: zTicketsConfig.partial().optional(),
  overrides: z.array(zPluginOverride).optional(),
  replaceDefaultOverrides: z
    .boolean()
    .optional()
    .describe("When true, ignore Dreamliner's built-in default level grants for this plugin."),
});

export type TicketsPluginSection = z.infer<typeof zTicketsPluginSection>;
